export const ON_DOWNLOAD_IMAGE = 'ON_DOWNLOAD_IMG';
export const GET_IMAGES = 'GET_IMAGES';
export const SENDING_IMAGE = 'SENDING_IMAGE';
export const REQUEST_IMAGES = 'REQUEST_IMAGES';
export const POST_IMAGE = 'POST_IMAGE';
